# Model parameters
IMG_HEIGHT = 299  
IMG_WIDTH = 299
BATCH_SIZE = 16  
EPOCHS = 150  
INITIAL_LEARNING_RATE = 1e-3  
FINE_TUNING_LEARNING_RATE = 1e-5  
WEIGHT_DECAY = 2e-4  

# Data parameters
TRAIN_PATH = 'data/train'
TEST_PATH = 'data/test'
VALIDATION_SPLIT = 0.2  

# Augmentation parameters (more conservative)
ROTATION_RANGE = 15
SHIFT_RANGE = 0.15
ZOOM_RANGE = 0.15
HORIZONTAL_FLIP = True
VERTICAL_FLIP = True
BRIGHTNESS_RANGE = [0.9, 1.1]